name: Hello-Java-Script-Action
description: 'random description'

inputs:

  remote-repo:
    description: remote repository
    required: true
    default: sashosotirov/kubernetes_wildfly

  remote-file:
    description: remote file to copy content
    required: true
    default: README.md

  current-file:
    description: current file to update content
    required: true
    default: README.md

  myToken:
    description: The PAT access token
    required: false

  # repository:
  #   description: blabla
  #   required: true
  # owner: 
  #   required: true
  pull_request_number:
    description: github context for PRN
    required: true

outputs:
  time:
    description: The time we greeted you

runs:
  using: 'node16'
  main: 'dist/index.js'